### ISSUE TITLE
environment file is missing and also git clone is not pulling all files from repo

### ISSUE THREAD

**Issue by ManojkumarM1** [Tencent/HunyuanVideo#156]
Hi i am trying to run the models in vast.ai. It worked fine 18 days back. now when i try to run things i am getting lot of missing files after git clone. As you can see below. Am i doing something wrong?  Also once i manually installed most of them and finally the model ran but got "norm" error message. 
P.s: Not a techie, new to coding. 
Any help is appreciated

t@C.14879372:/HunyuanVideo$ conda env create -f environment.yml

EnvironmentFileNotFound: '/HunyuanVideo/environment.yml' file not found

root@C.14879372:/HunyuanVideo$

**Comment by ManojkumarM1** [comment]
The "norm" error i referred to is show below

Traceback (most recent call last):

  File "/HunyuanVideo/sample_video.py", line 58, in <module>

    main()

  File "/HunyuanVideo/sample_video.py", line 25, in main

    hunyuan_video_sampler = HunyuanVideoSampler.from_pretrained(models_root_path, args=args)

  File "/HunyuanVideo/hyvideo/inference.py", line 241, in from_pretrained

    text_encoder = TextEncoder(

  File "/HunyuanVideo/hyvideo/text_encoder/__init__.py", line 180, in __init__

    self.model, self.model_path = load_text_encoder(

  File "/HunyuanVideo/hyvideo/text_encoder/__init__.py", line 39, in load_text_encoder

    text_encoder.final_layer_norm = text_encoder.norm

  File "/opt/conda/envs/HunyuanVideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__

    raise AttributeError(

AttributeError: 'CLIPModel' object has no attribute 'norm'

**Comment by complexfilter** [comment]
same here.

**Comment by AvisP** [comment]
There doesn't seem to be any `enviornment.yml` file in the repo but you guys can put the following into a requirements.txt file and create a virtual environment and pip install the packages from there on a linux environment or on wsl. It is from an environment where it is working for me

```
accelerate @ git+https://github.com/huggingface/accelerate.git@d6d3e03cd4868b1f69d4f334ddd341e4d414c342
aiohttp==3.8.3
aiosignal==1.3.2
aiostream==0.4.4
anyio==4.7.0
asgiref==3.5.2
asttokens==3.0.0
async-timeout==4.0.3
attrs==24.3.0
beautifulsoup4==4.12.3
blinker==1.9.0
certifi==2024.12.14
charset-normalizer==2.1.1
click==8.1.7
cloudpickle==2.2.0
commonmark==0.9.1
decorator==5.1.1
diffusers @ git+https://github.com/huggingface/diffusers.git@1b202c5730631417000585e3639539cefc79cbd7
DistVAE==0.0.0b4
einops==0.8.0
executing==2.1.0
fastapi==0.88.0
fastprogress==1.0.0
filelock==3.16.1
flash-attn==2.7.2.post1
Flask==3.1.0
frozenlist==1.5.0
fsspec==2024.12.0
gitdb==4.0.11
GitPython==3.1.43
grpclib==0.4.3
h2==4.1.0
hf_transfer==0.1.8
hpack==4.0.0
huggingface-hub==0.27.0
hyperframe==6.0.1
idna==3.10
imageio==2.36.1
imageio-ffmpeg==0.5.1
importlib-metadata==4.8.1
iniconfig==2.0.0
inquirerpy==0.3.4
ipython==8.31.0
itsdangerous==2.2.0
jedi==0.19.2
Jinja2==3.1.5
loguru==0.7.3
MarkupSafe==3.0.2
matplotlib-inline==0.1.7
modal==0.63.89
mpmath==1.3.0
multidict==6.1.0
networkx==3.4.2
ninja==1.11.1.3
numpy==2.2.0
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
opencv-python==4.10.0.84
optimum-quanto==0.2.6
packaging==24.2
parso==0.8.4
peft==0.14.0
pexpect==4.9.0
pfzy==0.3.4
pillow==11.0.0
pluggy==1.5.0
prompt_toolkit==3.0.48
propcache==0.2.1
protobuf==5.29.2
psutil==6.1.1
ptyprocess==0.7.0
pure_eval==0.2.3
pydantic==1.10.19
Pygments==2.18.0
pytest==8.3.4
python-multipart==0.0.20
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
rich==12.3.0
safetensors==0.4.5
sentencepiece==0.2.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
starlette==0.22.0
sympy==1.13.1
tblib==1.7.0
tokenizers==0.21.0
toml==0.10.2
torch==2.5.1
torchvision==0.20.1
tqdm==4.67.1
traitlets==5.14.3
transformers==4.47.1
triton==3.1.0
typeguard==4.4.1
typer==0.6.1
types-certifi==2021.10.8.3
types-toml==0.10.4
typing_extensions==4.12.2
urllib3==2.3.0
wcwidth==0.2.13
Werkzeug==3.1.3
xfuser==0.4.0
yarl==1.18.3
yunchang==0.6.0
zipp==3.21.0
```
