### ISSUE TITLE
FP8 Inference

### ISSUE THREAD

**Issue by zsxkib** [Tencent/HunyuanVideo#21]
Hello,

First of all, thank you for open-sourcing the HunyuanVideo model and providing the inference code and model weights. I'm excited to experiment with it and leverage the capabilities of modern GPUs.

**Issue Summary:**

I'm attempting to run the HunyuanVideo model using FP8 precision to take advantage of the performance benefits on NVIDIA H100/H200 GPUs. However, I've encountered issues while modifying the codebase to support FP8 inference and would appreciate guidance on the proper way to implement this.

**What I've Tried:**

1. **Updated `constants.py`:**

   - Added `'fp8'` to the `PRECISIONS` set.
   - Updated `PRECISION_TO_TYPE` to include FP8 mapping.

   ```python
   # constants.py

   PRECISIONS = {"fp32", "fp16", "bf16", "fp8"}

   PRECISION_TO_TYPE = {
       "fp32": torch.float32,
       "fp16": torch.float16,
       "bf16": torch.bfloat16,
       "fp8": torch.float8_e4m3fn,
   }
   ```

2. **Modified `inference.py`:**

   - Adjusted the `load_vae` call to remove the `dtype` parameter, as it wasn't accepted by the function.
   - Wrapped inference calls in an `autocast` context with FP8 dtype when FP8 precision is specified.

   ```python
   # inference.py

   from torch.cuda.amp import autocast

   class Inference(object):
       # ...

       @torch.no_grad()
       def predict(self, prompt, height=192, width=336, video_length=129, **kwargs):
           # ...

           # Use autocast for FP8 computations if specified
           dtype = torch.float8_e4m3fn if self.args.precision == 'fp8' else None
           with autocast(device_type=self.device, dtype=dtype, enabled=dtype is not None):
               samples = self.pipeline(
                   prompt=prompt,
                   height=target_height,
                   width=target_width,
                   video_length=target_video_length,
                   num_inference_steps=infer_steps,
                   guidance_scale=guidance_scale,
                   negative_prompt=negative_prompt,
                   num_videos_per_prompt=num_videos_per_prompt,
                   generator=generator,
                   output_type="pil",
                   freqs_cis=(freqs_cos, freqs_sin),
                   n_tokens=n_tokens,
                   embedded_guidance_scale=embedded_guidance_scale,
                   data_type="video" if target_video_length > 1 else "image",
                   is_progress_bar=True,
                   vae_ver=self.args.vae,
                   enable_tiling=self.args.vae_tiling,
               )[0]
           # ...
   ```

3. **Attempted to Initialize the Model with FP8 Precision:**

   - Set the `dtype` for model initialization to `torch.float8_e4m3fn`.

**The Problem:**

When running the modified code, I encounter the following error during model initialization:

```
Traceback (most recent call last):
  File "/src/sample_video.py", line 57, in <module>
    main()
  File "/src/sample_video.py", line 25, in main
    hunyuan_video_sampler = HunyuanVideoSampler.from_pretrained(models_root_path, args=args)
  File "/src/hyvideo/inference.py", line 78, in from_pretrained
    model = load_model(
  File "/src/hyvideo/modules/__init__.py", line 17, in load_model
    model = HYVideoDiffusionTransformer(
  File "/path_to_torch/nn/modules/conv.py", line 588, in __init__
    super().__init__(
  File "/path_to_torch/nn/modules/conv.py", line 141, in __init__
    self.reset_parameters()
  File "/path_to_torch/nn/modules/conv.py", line 147, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/path_to_torch/nn/init.py", line 419, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
RuntimeError: "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
```

**Research and Findings:**

- The error suggests that PyTorch's initialization functions, like `kaiming_uniform_`, do not support FP8 tensors directly.
- Similar issues have been discussed in this [StackOverflow post](https://stackoverflow.com/questions/76171206/pytorch-runtimeerror-check-uniform-bounds-not-implemented-for-int).

**My Understanding:**

- Model parameters cannot be directly stored in FP8 format due to initialization constraints and potential precision loss.
- Computations can be performed in FP8 using `autocast`, while keeping model parameters in a higher precision like FP16 or BF16.
- Attempting to initialize the model weights directly in FP8 leads to the aforementioned error.

**My Questions:**

1. **What is the recommended way to enable FP8 inference with the HunyuanVideo model on H100/H200 GPUs?**

   - Should I initialize the model parameters in FP16/BF16 and then perform computations in FP8 using `autocast`?
   - Are there specific modifications needed in the model or pipeline code to properly support FP8 computations?

2. **Has anyone successfully implemented FP8 inference with this model, and if so, could you share guidance or examples on how to achieve this?**

**Additional Context:**

- I'm using PyTorch version >= 2.0 and CUDA version >= 12.0.
- The goal is to leverage FP8 support on NVIDIA H100/H200 GPUs for faster inference.
- I have tested with `torch.float8_e4m3fn` for FP8 precision.

**Any guidance or suggestions on how to properly implement FP8 inference support would be greatly appreciated.**

Thank you for your time and for making this model available to the community!

Best regards,

Sakib

---

**Environment Details:**

- **PyTorch Version:** [e.g., 2.1.0]
- **CUDA Version:** [e.g., 12.1]
- **GPU Model:** [e.g., NVIDIA H100]
- **Python Version:** [e.g., 3.10]
- **Operating System:** [e.g., Ubuntu 20.04]

**Reproduction Steps:**

1. Clone the HunyuanVideo repository.
2. Apply the code modifications as described above to support FP8 precision.
3. Run the sample video generation script with `--precision fp8`.
4. Observe the error during model initialization.

**Command Used:**

```bash
python3 sample_video.py \
    --video-size 720 1280 \
    --video-length 129 \
    --infer-steps 50 \
    --prompt "A cat walks on the grass, realistic style." \
    --flow-reverse \
    --flow-shift 7.0 \
    --seed 0 \
    --use-cpu-offload \
    --precision fp8 \
    --save-path ./results
```

P.S. To be clear the model works and runs, it's just a bit slow on my H100s

**Comment by zhoudaquan** [comment]
> Hello,
> 
> First of all, thank you for open-sourcing the HunyuanVideo model and providing the inference code and model weights. I'm excited to experiment with it and leverage the capabilities of modern GPUs.
> 
> **Issue Summary:**
> 
> I'm attempting to run the HunyuanVideo model using FP8 precision to take advantage of the performance benefits on NVIDIA H100/H200 GPUs. However, I've encountered issues while modifying the codebase to support FP8 inference and would appreciate guidance on the proper way to implement this.
> 
> **What I've Tried:**
> 
> 1. **Updated `constants.py`:**
>    
>    * Added `'fp8'` to the `PRECISIONS` set.
>    * Updated `PRECISION_TO_TYPE` to include FP8 mapping.
>    
>    ```python
>    # constants.py
>    
>    PRECISIONS = {"fp32", "fp16", "bf16", "fp8"}
>    
>    PRECISION_TO_TYPE = {
>        "fp32": torch.float32,
>        "fp16": torch.float16,
>        "bf16": torch.bfloat16,
>        "fp8": torch.float8_e4m3fn,
>    }
>    ```
> 2. **Modified `inference.py`:**
>    
>    * Adjusted the `load_vae` call to remove the `dtype` parameter, as it wasn't accepted by the function.
>    * Wrapped inference calls in an `autocast` context with FP8 dtype when FP8 precision is specified.
>    
>    ```python
>    # inference.py
>    
>    from torch.cuda.amp import autocast
>    
>    class Inference(object):
>        # ...
>    
>        @torch.no_grad()
>        def predict(self, prompt, height=192, width=336, video_length=129, **kwargs):
>            # ...
>    
>            # Use autocast for FP8 computations if specified
>            dtype = torch.float8_e4m3fn if self.args.precision == 'fp8' else None
>            with autocast(device_type=self.device, dtype=dtype, enabled=dtype is not None):
>                samples = self.pipeline(
>                    prompt=prompt,
>                    height=target_height,
>                    width=target_width,
>                    video_length=target_video_length,
>                    num_inference_steps=infer_steps,
>                    guidance_scale=guidance_scale,
>                    negative_prompt=negative_prompt,
>                    num_videos_per_prompt=num_videos_per_prompt,
>                    generator=generator,
>                    output_type="pil",
>                    freqs_cis=(freqs_cos, freqs_sin),
>                    n_tokens=n_tokens,
>                    embedded_guidance_scale=embedded_guidance_scale,
>                    data_type="video" if target_video_length > 1 else "image",
>                    is_progress_bar=True,
>                    vae_ver=self.args.vae,
>                    enable_tiling=self.args.vae_tiling,
>                )[0]
>            # ...
>    ```
> 3. **Attempted to Initialize the Model with FP8 Precision:**
>    
>    * Set the `dtype` for model initialization to `torch.float8_e4m3fn`.
> 
> **The Problem:**
> 
> When running the modified code, I encounter the following error during model initialization:
> 
> ```
> Traceback (most recent call last):
>   File "/src/sample_video.py", line 57, in <module>
>     main()
>   File "/src/sample_video.py", line 25, in main
>     hunyuan_video_sampler = HunyuanVideoSampler.from_pretrained(models_root_path, args=args)
>   File "/src/hyvideo/inference.py", line 78, in from_pretrained
>     model = load_model(
>   File "/src/hyvideo/modules/__init__.py", line 17, in load_model
>     model = HYVideoDiffusionTransformer(
>   File "/path_to_torch/nn/modules/conv.py", line 588, in __init__
>     super().__init__(
>   File "/path_to_torch/nn/modules/conv.py", line 141, in __init__
>     self.reset_parameters()
>   File "/path_to_torch/nn/modules/conv.py", line 147, in reset_parameters
>     init.kaiming_uniform_(self.weight, a=math.sqrt(5))
>   File "/path_to_torch/nn/init.py", line 419, in kaiming_uniform_
>     return tensor.uniform_(-bound, bound)
> RuntimeError: "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
> ```
> 
> **Research and Findings:**
> 
> * The error suggests that PyTorch's initialization functions, like `kaiming_uniform_`, do not support FP8 tensors directly.
> * Similar issues have been discussed in this [StackOverflow post](https://stackoverflow.com/questions/76171206/pytorch-runtimeerror-check-uniform-bounds-not-implemented-for-int).
> 
> **My Understanding:**
> 
> * Model parameters cannot be directly stored in FP8 format due to initialization constraints and potential precision loss.
> * Computations can be performed in FP8 using `autocast`, while keeping model parameters in a higher precision like FP16 or BF16.
> * Attempting to initialize the model weights directly in FP8 leads to the aforementioned error.
> 
> **My Questions:**
> 
> 1. **What is the recommended way to enable FP8 inference with the HunyuanVideo model on H100/H200 GPUs?**
>    
>    * Should I initialize the model parameters in FP16/BF16 and then perform computations in FP8 using `autocast`?
>    * Are there specific modifications needed in the model or pipeline code to properly support FP8 computations?
> 2. **Has anyone successfully implemented FP8 inference with this model, and if so, could you share guidance or examples on how to achieve this?**
> 
> **Additional Context:**
> 
> * I'm using PyTorch version >= 2.0 and CUDA version >= 12.0.
> * The goal is to leverage FP8 support on NVIDIA H100/H200 GPUs for faster inference.
> * I have tested with `torch.float8_e4m3fn` for FP8 precision.
> 
> **Any guidance or suggestions on how to properly implement FP8 inference support would be greatly appreciated.**
> 
> Thank you for your time and for making this model available to the community!
> 
> Best regards,
> 
> Sakib
> 
> **Environment Details:**
> 
> * **PyTorch Version:** [e.g., 2.1.0]
> * **CUDA Version:** [e.g., 12.1]
> * **GPU Model:** [e.g., NVIDIA H100]
> * **Python Version:** [e.g., 3.10]
> * **Operating System:** [e.g., Ubuntu 20.04]
> 
> **Reproduction Steps:**
> 
> 1. Clone the HunyuanVideo repository.
> 2. Apply the code modifications as described above to support FP8 precision.
> 3. Run the sample video generation script with `--precision fp8`.
> 4. Observe the error during model initialization.
> 
> **Command Used:**
> 
> ```shell
> python3 sample_video.py \
>     --video-size 720 1280 \
>     --video-length 129 \
>     --infer-steps 50 \
>     --prompt "A cat walks on the grass, realistic style." \
>     --flow-reverse \
>     --flow-shift 7.0 \
>     --seed 0 \
>     --use-cpu-offload \
>     --precision fp8 \
>     --save-path ./results
> ```
> 
> P.S. To be clear the model works and runs, it's just a bit slow on my H100s

Hey Bro,

Thanks for your detailed explanation on the efforts you have put into this! FYI, we are verifying different levels of acceleration techniques, including varying levels of quantization, and will update this repo after getting approval from the company. At the same times, you are more than welcome to contribute to this repo!

Best regards,
DQ

**Comment by nitinmukesh** [comment]
@zsxkib 

Fp8 model is already available
https://huggingface.co/Kijai/HunyuanVideo_comfy/tree/main

**Comment by zsxkib** [comment]
thanks @nitinmukesh, i'm already using it now :D
fp8 wasn't available on the day of posting

**Comment by nitinmukesh** [comment]
@zsxkib 

Are you using in Comfyi or custom code.
