### ISSUE TITLE
error:  vae.load_state_dict(vae_ckpt)

### ISSUE THREAD

**Issue by zhouzhenneng** [Tencent/HunyuanVideo#64]
Hello, when I run the following command on the Linux server:

```
python sample_video.py --video-size 720 1280 --video-length 129 --infer-steps 50 --prompt "A cat walks on the grass, realistic style."  --flow-reverse --use-cpu-offload --save-path./results
```

I got the following error messages:

```
2024-12-05 12:37:56.346 | INFO     | hyvideo.inference:from_pretrained:73 - Building model...
2024-12-05 12:37:56.536 | INFO     | hyvideo.inference:load_state_dict:221 - Loading torch model ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt...
2024-12-05 12:38:16.664 | INFO     | hyvideo.vae:load_vae:29 - Loading 3D VAE model (884-16c-hy) from:./ckpts/hunyuan-video-t2v-720p/vae
vae_ckpt path: ckpts/hunyuan-video-t2v-720p/vae/pytorch_model.pt
vae_ckpt: {}
Traceback (most recent call last):
  File "/opt/HunyuanVideo/sample_video.py", line 57, in <module>
    main()
  File "/opt/HunyuanVideo/sample_video.py", line 25, in main
    hunyuan_video_sampler = HunyuanVideoSampler.from_pretrained(models_root_path, args=args)
  File "/opt/HunyuanVideo/hyvideo/inference.py", line 90, in from_pretrained
    vae, _, s_ratio, t_ratio = load_vae(
  File "/opt/HunyuanVideo/hyvideo/vae/__init__.py", line 46, in load_vae
    vae.load_state_dict(vae_ckpt)
  File "/root/miniconda3/envs/HunyuanVideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKLCausal3D:
        Missing key(s) in state_dict: "encoder.conv_in.conv.weight", "encoder.conv_in.conv.bias"......
```

I printed some information where the error occurred in `HunyuanVideo/hyvideo/vae/__init__.py` as follows:

```python
vae_ckpt = Path(vae_path) / "pytorch_model.pt"
print(f"vae_ckpt path: {vae_ckpt}")
assert vae_ckpt.exists(), f"VAE checkpoint not found: {vae_ckpt}"

ckpt = torch.load(vae_ckpt, map_location=vae.device)
# print(f"ckpt: {ckpt}")
if "state_dict" in ckpt:
    ckpt = ckpt["state_dict"]
vae_ckpt = {k.replace("vae.", ""): v for k, v in ckpt.items() if k.startswith("vae.")}
print(f"vae_ckpt: {vae_ckpt}")
vae.load_state_dict(vae_ckpt)
```

The printed information is as follows:

```
vae_ckpt path: ckpts/hunyuan-video-t2v-720p/vae/pytorch_model.pt
vae_ckpt: {}
```

I followed all the installation steps as indicated in the README. The running environment I'm using is:
 Linux Centos
Torch version: 2.1.1
CUDA version: 12.1

**Comment by Changlin-Lee** [comment]
Hi, we have fixed this issue in the newest commit: https://github.com/Tencent/HunyuanVideo/blob/main/hyvideo/vae/__init__.py#L42

Git pull may fix this problem.

**Comment by zhouzhenneng** [comment]
> Hi, we have fixed this issue in the newest commit: https://github.com/Tencent/HunyuanVideo/blob/main/hyvideo/vae/__init__.py#L42
> 
> Git pull may fix this problem.

it works, Thanks!
