### ISSUE TITLE
cuda 11.8 + torch 2.5.0 attention cudnn error in token_refiner

### ISSUE THREAD

**Issue by feifeibear** [Tencent/HunyuanVideo#77]
I encounter the following error when using cuda 11.8 + torch 2.5. If I use the vanilla attention it will successfully run.
I downgrade torch to 2.4.0 everything is fine.

  
  0%|          | 0/50 [00:00<?, ?it/s]2024-12-05 08:26:00.703 | INFO     | hyvideo.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: ./ckpts/text_encoder
2024-12-05 08:26:01.026 | INFO     | hyvideo.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: ./ckpts/text_encoder_2

  0%|          | 0/50 [00:00<?, ?it/s]
[rank7]: Traceback (most recent call last):
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/sample_video.py", line 57, in <module>
[rank7]:     main()
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/sample_video.py", line 32, in main
[rank7]:     outputs = hunyuan_video_sampler.predict(
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank7]:     return func(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/inference.py", line 637, in predict
[rank7]:     samples = self.pipeline(
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank7]:     return func(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 991, in __call__
[rank7]:     noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/inference.py", line 74, in new_forward
[rank7]:     output = original_forward(
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/modules/models.py", line 678, in forward
[rank7]:     txt = self.txt_in(txt, t, text_mask if self.use_attention_mask else None)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/modules/token_refiner.py", line 234, in forward
[rank7]:     x = self.individual_token_refiner(x, c, mask)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/modules/token_refiner.py", line 160, in forward
[rank7]:     x = block(x, c, self_attn_mask)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/reaper/miniconda3/envs/hy2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/modules/token_refiner.py", line 93, in forward
[rank7]:     attn = attention(q, k, v, mode="torch", attn_mask=attn_mask)
[rank7]:   File "/dev/shm/models/HunyuanVideo-xDiT/hyvideo/modules/attenion.py", line 100, in attention
[rank7]:     x = F.scaled_dot_product_attention(
[rank7]: RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.

**Comment by feifeibear** [comment]
we fixed this error with torch 2.4.0
